### PR TITLE
Added flag to enable htaccess rewritebase

### LINKED ISSUE #14: Option for removing "index.php" from URL (aka rewritebase)
Currently the URL of a provisioned instance always shows "index.php" in the URL.
There's an option to make it cleaner.

To make this work, I had to manually do the following on the provisioned instance:

- edit config.php and add a key `'htaccess.RewriteBase' => '/'`
- run `sudo -u www-data ./occ maintenance:update:htaccess`

### PR DESCRIPTION
**Pull request by PVince81**
Fixes #14

### CODE REVIEW

**Comment by PVince81** [comment]
- [x] TODO: how to regenerate README.md => seems it's done in Drone
- [x] BUG: some errors when running grep

**Comment by PVince81** [comment]
- [ ] what to do in migration cases, for setups that exist before this change ?
   - because the default was false (no htaccess.rewritebase) but now the default becomes true ?
   - should we also set the default to false ?
   - :warning: note that this setting will change the format of the URLs, so formerly shared public links might not work any more if they contained no index.php but now index.php is needed

**Comment by PVince81** [comment]
I have some issues with the condition for running "occ maintenance:update:htaccess":
The debug output does show that the two values / conditions are different, however when used in a `when` statement, it doesn't seem to detect the difference.

This is the output:
```
TASK [owncloud : Get current htaccess rewrite state from .htaccess file] *******
ok: [owncloud1] => {"changed": false, "cmd": ["/bin/grep", "RewriteBase /", "/var/www/owncloud/.htaccess"], "delta": "0:00:00.005805", "end": "2019-11-30 21:07:03.277409", "failed_when_result": false, "msg": "non-zero return code", "rc": 1, "start": "2019-11-30 21:07:03.271604", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}                                                          

TASK [owncloud : debug] ********************************************************
ok: [owncloud1] => {
    "msg": [
        "### owncloud_register_htaccess_rewrite_check = {'stderr_lines': [], u'cmd': [u'/bin/grep', u'RewriteBase /', u'/var/www/owncloud/.htaccess'], u'end': u'2019-11-30 21:07:03.277409', u'stdout': u'', u'changed': False, u'rc': 1, u'failed': False, u'stderr': u'', u'delta': u'0:00:00.005805', u'msg': u'non-zero return code', 'stdout_lines': [], 'failed_when_result': False, u'start': u'2019-11-30 21:07:03.271604'}",                                                                                                                      
        "### RewriteBase present ? False", 
        "### owncloud_rewrite_base_enabled = True"
    ]
}

TASK [owncloud : Update htaccess rewrite rules] ********************************
skipping: [owncloud1] => {"changed": false, "skip_reason": "Conditional result was False"}
```

Then when condition is here: https://github.com/owncloud-ansible/owncloud/pull/15/files#diff-8f75a630e519e3c8689f860696b06c61R50

According to the debug output above that uses the same conditions, the "when" condition should evaluate to `False != True` so it should run the command.

If I explicitly write `False != True` it works... So maybe something is weird in my expression ?

**Comment by PVince81** [comment]
- [ ] TODO: adjust molecule tests and remove "index.php" there ? (assuming removing index.php is by default)

**Comment by PVince81** [comment]
problem with the condition solved: I was assuming that the value of "owncloud_rewrite_base_enabled" was a boolean but it was actually a string...

**Comment by TheRealBro** [comment]
I guess this needs a complete rewrite to fix #14

**Pull request closed without merging**
